#!/usr/bin/python
import os
import sys
import subprocess

from taskloaf_scripts import build_dir, get_n_cores

dir = build_dir(sys.argv[1])

os.chdir(dir)
p = subprocess.Popen(['make', 'test'])
p.wait()
