#!/bin/bash

# Install gcc 4.9
sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
sudo apt-get -qq update
sudo apt-get -qq install g++-4.9

if [ "$INSTALL_MPI" ]; then 
    sudo apt-get install -qq libopenmpi-dev openmpi-bin;
fi

sed -i 's/git@github.com:/https:\/\/github.com\//' CMakeLists.txt
