#!/bin/bash
# This script should be run when new versions of the header-only dependencies
# are desired.

git clone --depth 1 git@github.com:USCiLab/cereal.git cereal_git
[ -d cereal ] && rm -r cereal
mv cereal_git/include/cereal ./cereal
rm -rf cereal_git

git clone --depth 1 git@github.com:onqtam/doctest.git
cp doctest/doctest/doctest.h ./
rm -rf doctest

git clone --depth 1 git@github.com:cameron314/concurrentqueue.git
mv concurrentqueue/concurrentqueue.h ./
rm -rf concurrentqueue
