#!/bin/bash
# This script should be run when new versions of the header-only dependencies
# are desired.

git clone --depth 1 git@github.com:USCiLab/cereal.git cereal_git
[ -d cereal ] && rm -r cereal
mv cereal_git/include/cereal ./cereal
rm -rf cereal_git

git clone --depth 1 git@github.com:philsquared/Catch.git
cp Catch/single_include/catch.hpp ./
rm -rf Catch

git clone --depth 1 git@github.com:cameron314/concurrentqueue.git
mv concurrentqueue/concurrentqueue.h ./
rm -rf concurrentqueue

git clone --depth 1 git@github.com:pybind/pybind11.git pybind11_git
[ -d pybind11 ] && rm -r pybind11
mv pybind11_git/include/pybind11 ./pybind11
rm -rf pybind11_git
